/**
 * Pipeline: Content Enhancement Tests
 *
 * Tests the 6 enhanced fields generated by the analysis agent:
 * - program_overview: short summary
 * - program_insights: strategic insights
 * - eligibility_criteria: structured eligibility
 * - application_process: step-by-step process
 * - key_dates: important dates
 * - contact_information: contact details
 *
 * NOTE: Since LLM generates these, we test schema compliance, not content.
 */

import { describe, test, expect } from 'vitest';

const ENHANCED_FIELDS = [
  'program_overview',
  'program_insights',
  'eligibility_criteria',
  'application_process',
  'key_dates',
  'contact_information',
];

/**
 * Validate that enhanced content has all required fields
 */
function validateEnhancedContent(content) {
  const errors = [];

  for (const field of ENHANCED_FIELDS) {
    if (!(field in content)) {
      errors.push(`Missing field: ${field}`);
    } else if (content[field] !== null && typeof content[field] !== 'string') {
      errors.push(`Field ${field}: expected string or null, got ${typeof content[field]}`);
    }
  }

  return errors;
}

/**
 * Check if content was actually enhanced (not just empty/null)
 */
function calculateEnhancementCoverage(content) {
  let filled = 0;
  for (const field of ENHANCED_FIELDS) {
    if (content[field] && content[field].trim().length > 0) {
      filled++;
    }
  }
  return {
    total: ENHANCED_FIELDS.length,
    filled,
    coverage: filled / ENHANCED_FIELDS.length,
  };
}

/**
 * Merge enhanced content with existing opportunity data
 */
function mergeEnhancedContent(original, enhanced) {
  const merged = { ...original };

  for (const field of ENHANCED_FIELDS) {
    if (enhanced[field] && enhanced[field].trim().length > 0) {
      merged[field] = enhanced[field];
    }
    // Don't overwrite existing values with empty/null
  }

  return merged;
}

/**
 * Sanitize enhanced content (remove artifacts)
 */
function sanitizeEnhancedContent(content) {
  const sanitized = {};

  for (const field of ENHANCED_FIELDS) {
    let value = content[field];
    if (typeof value === 'string') {
      value = value.trim();
      // Remove common LLM artifacts
      value = value.replace(/^(Here is|Here's|The following|Below is)[^:]*:\s*/i, '');
      value = value.replace(/\n{3,}/g, '\n\n');
      sanitized[field] = value || null;
    } else {
      sanitized[field] = null;
    }
  }

  return sanitized;
}

describe('Content Enhancement', () => {

  describe('Schema Validation', () => {
    test('validates complete enhanced content', () => {
      const content = {
        program_overview: 'A federal grant for clean energy projects.',
        program_insights: 'High competition. Focus on DAC communities.',
        eligibility_criteria: 'Local governments and utilities eligible.',
        application_process: 'Submit via Grants.gov by June 30.',
        key_dates: 'Application deadline: June 30, 2025.',
        contact_information: 'contact@grants.gov',
      };

      const errors = validateEnhancedContent(content);
      expect(errors).toHaveLength(0);
    });

    test('allows null fields', () => {
      const content = {
        program_overview: 'Summary here.',
        program_insights: null,
        eligibility_criteria: null,
        application_process: null,
        key_dates: null,
        contact_information: null,
      };

      const errors = validateEnhancedContent(content);
      expect(errors).toHaveLength(0);
    });

    test('rejects missing fields', () => {
      const content = { program_overview: 'Just one field' };
      const errors = validateEnhancedContent(content);
      expect(errors.length).toBe(5); // 5 missing fields
    });

    test('rejects non-string field values', () => {
      const content = {
        program_overview: 123,
        program_insights: '',
        eligibility_criteria: '',
        application_process: '',
        key_dates: '',
        contact_information: '',
      };

      const errors = validateEnhancedContent(content);
      expect(errors.length).toBe(1);
      expect(errors[0]).toContain('program_overview');
    });

  });

  describe('Enhancement Coverage', () => {
    test('full coverage when all fields filled', () => {
      const content = {};
      ENHANCED_FIELDS.forEach(f => { content[f] = 'some content'; });

      const result = calculateEnhancementCoverage(content);
      expect(result.filled).toBe(6);
      expect(result.coverage).toBe(1.0);
    });

    test('zero coverage when all null', () => {
      const content = {};
      ENHANCED_FIELDS.forEach(f => { content[f] = null; });

      const result = calculateEnhancementCoverage(content);
      expect(result.filled).toBe(0);
      expect(result.coverage).toBe(0);
    });

    test('partial coverage calculated correctly', () => {
      const content = {
        program_overview: 'Summary',
        program_insights: 'Insights',
        eligibility_criteria: null,
        application_process: null,
        key_dates: null,
        contact_information: null,
      };

      const result = calculateEnhancementCoverage(content);
      expect(result.filled).toBe(2);
      expect(result.coverage).toBeCloseTo(0.333, 2);
    });

    test('whitespace-only counts as not filled', () => {
      const content = {
        program_overview: '   ',
        program_insights: '\n\n',
        eligibility_criteria: '',
        application_process: null,
        key_dates: null,
        contact_information: null,
      };

      const result = calculateEnhancementCoverage(content);
      expect(result.filled).toBe(0);
    });
  });

  describe('Content Merging', () => {
    test('enhanced content overwrites original', () => {
      const original = { id: '1', program_overview: 'Old summary' };
      const enhanced = { program_overview: 'New summary' };
      ENHANCED_FIELDS.forEach(f => { if (!(f in enhanced)) enhanced[f] = null; });

      const merged = mergeEnhancedContent(original, enhanced);
      expect(merged.program_overview).toBe('New summary');
    });

    test('preserves original non-enhanced fields', () => {
      const original = { id: '1', title: 'My Grant', program_overview: 'Old' };
      const enhanced = {};
      ENHANCED_FIELDS.forEach(f => { enhanced[f] = null; });

      const merged = mergeEnhancedContent(original, enhanced);
      expect(merged.id).toBe('1');
      expect(merged.title).toBe('My Grant');
    });

    test('does not overwrite with empty string', () => {
      const original = { program_overview: 'Existing summary' };
      const enhanced = { program_overview: '   ' };
      ENHANCED_FIELDS.forEach(f => { if (!(f in enhanced)) enhanced[f] = null; });

      const merged = mergeEnhancedContent(original, enhanced);
      expect(merged.program_overview).toBe('Existing summary');
    });
  });

  describe('Content Sanitization', () => {
    test('trims whitespace', () => {
      const content = { program_overview: '  Summary here  ' };
      ENHANCED_FIELDS.forEach(f => { if (!(f in content)) content[f] = null; });

      const sanitized = sanitizeEnhancedContent(content);
      expect(sanitized.program_overview).toBe('Summary here');
    });

    test('removes LLM prefix artifacts', () => {
      const content = {
        program_overview: 'Here is a summary of the program: This is a clean energy grant.',
      };
      ENHANCED_FIELDS.forEach(f => { if (!(f in content)) content[f] = null; });

      const sanitized = sanitizeEnhancedContent(content);
      expect(sanitized.program_overview).toBe('This is a clean energy grant.');
    });

    test('collapses excessive newlines', () => {
      const content = { program_overview: 'Line 1\n\n\n\n\nLine 2' };
      ENHANCED_FIELDS.forEach(f => { if (!(f in content)) content[f] = null; });

      const sanitized = sanitizeEnhancedContent(content);
      expect(sanitized.program_overview).toBe('Line 1\n\nLine 2');
    });

    test('empty string becomes null', () => {
      const content = { program_overview: '' };
      ENHANCED_FIELDS.forEach(f => { if (!(f in content)) content[f] = null; });

      const sanitized = sanitizeEnhancedContent(content);
      expect(sanitized.program_overview).toBeNull();
    });
  });
});
