'use client';

import React from 'react';
import { View, Text } from '@react-pdf/renderer';
import { styles } from '../styles/pdfStyles';
import { formatDate } from '../utils/formatters';

/**
 * Page Footer Component
 *
 * Displays on each page with branding and page numbers
 */
export function PageFooter() {
  return (
    <View style={styles.pageFooter} fixed>
      <Text style={styles.footerText}>
        Generated by Meridian ESG | {formatDate(new Date(), 'medium')}
      </Text>
      <Text
        style={styles.pageNumber}
        render={({ pageNumber, totalPages }) => `Page ${pageNumber} of ${totalPages}`}
      />
    </View>
  );
}

export default PageFooter;
